Lab 1:Exception Handling

In [ ]:
div = 2/0

ZeroDivisionError: division by zero

In [ ]:
print("Hello", name)

NameError: name 'age' is not defined

In [ ]:
list1 = [1,2,3,4,5]
print(list1[10])

IndexError: list index out of range

In [ ]:
number= int(input("Enter a number: "))

Enter a number: n7!


ValueError: invalid literal for int() with base 10: 'n7!'

In [ ]:
dict1 = {1:10 , 2:20}
print(dict1[3])

KeyError: 3

In [ ]:
num= int(input("Enter a number: "))
ans= 10/num
print(ans)

Enter a number: 0


ZeroDivisionError: division by zero

In [ ]:
try:
    num= int(input("Enter a number: "))
    ans= 10/num
    print(ans)
except:
    print("Error! Do not enter Zero")
    print("Try again")

Enter a number: 0
Error! Do not enter Zero
Try again


In [ ]:
try:
    num= int(input("Enter a number: "))
    ans= 10/num
except:
    print("Error! Cannot divide.")
else:
    print("Answer is: ", ans)

Enter a number: 10
Answer is:  1.0


In [ ]:
try:
    num= int(input("Enter a number: "))
    ans= 10/num
except:
    print("Error! Cannot divide.")
else:
    print("Answer is: ", ans)
finally:
    print("Program finished!")

Enter a number: 10
Answer is:  1.0
Program finished!


In [ ]:
a = int(input("a = "))
b = int(input("b = "))
c = a/b
print("Result:", c)

In [ ]:
#Basic
try:
    a = int(input("a = "))
    b = int(input("b = "))
    c = a/b
    print("Result:", c)
except:
    print("Something went wrong! Try again!")

a = abc
Something went wrong! Try again!


In [ ]:
#Handle specific errors
try:
    a = int(input("a = "))
    b = int(input("b = "))
    c = a/b
    print("Result:", c)

except ZeroDivisionError:
    print("Make sure b is not 0.")

except ValueError:
    print("Enter integer values only! ")

except Exception:
    print("Error Ocurred: ")

In [ ]:
try:
    a=int(input('a='))
    b=int(input('b='))
    c=a/b

except ZeroDivisionError as z:
    pass

except ValueError as v:
    print(v)

except Exception as e:
    print(e)

else:
    print('The answer is: ', c)

finally:
    print('Program End!')

a=2
b=0
Program End!


In [ ]:
try:
    numbers = [10,20,30,40,50]
    index = int(input("Enter list index (0-4): "))
    print("Value at index: ", numbers[index])

except ValueError as v:
    print("Enter an integer!", v)

except IndexError as i:
    print("Number range 0 to 4!", i)

In [ ]:
def is_even(lst):
    even = []
    for i in lst:
        if i % 2 == 0:
            even.append(i)
    return even
print(is_even([1,2,3,4,5,6]))
print(is_even(23))

[2, 4, 6]


TypeError: 'int' object is not iterable

In [ ]:
def is_even(lst):
    even = []
    try:
        for i in lst:
            if i % 2 == 0:
                even.append(i)
        return even
    except TypeError:
        print("Please give a list!")

print(is_even([1,2,3,4,5,6]))
print(is_even(23))

[2, 4, 6]
Please give a list!
None


Lab 2:Array

In [ ]:
#Arrays are faster, support matrix operations.
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Accessing elements of the array
print(arr_1d[0]) # Accessing the first element
print(arr_1d[2]) # Accessing the third element

In [ ]:
# Accessing elements of the array
print(arr_2d[0][0]) # first row, first column
print(arr_2d[1][2]) # second row, third column

In [ ]:
print(arr_2d.reshape(1,6))

[[1 2 3 4 5 6]]


In [ ]:
# Performing operations on arrays
print(arr_1d+2)
print(arr_1d*2)
arr_sum2d = np.sum(arr_2d)
print("Sum of elements of 2D:", arr_sum2d)

[3 4 5 6 7]
[ 2  4  6  8 10]
Sum of elements of 2D: 21


In [ ]:
row = np.sum(arr_2d, axis=1)
print("Row wise sum:", row)
col = np.sum(arr_2d, axis=0)
print("Column wise sum:", col)